name: Test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [26.x ]
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and Test 🔧
        run: |
          npm ci
          npm run lint
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [26.x ]
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and benchmark 🔧
        run: |
          npm ci
          npm start -- -u https://www.google.com -a 10
